<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::insert(DB::raw("INSERT INTO `cities` (`id`, `name`, `province_id`, `created_at`, `updated_at`, `deleted_at`) VALUES
        (1, 'Kab. Simeulue', 1, NULL, '2019-09-04 09:41:18', NULL),
        (2, 'Kab. Aceh Singkil', 1, NULL, '2019-09-04 09:41:18', NULL),
        (3, 'Kab. Aceh Selatan', 1, NULL, '2019-09-04 09:41:18', NULL),
        (4, 'Kab. Aceh Tenggara', 1, NULL, '2019-09-04 09:41:18', NULL),
        (5, 'Kab. Aceh Timur', 1, NULL, '2019-09-04 09:41:18', NULL),
        (6, 'Kab. Aceh Tengah', 1, NULL, '2019-09-04 09:41:18', NULL),
        (7, 'Kab. Aceh Barat', 1, NULL, '2019-09-04 09:41:18', NULL),
        (8, 'Kab. Aceh Besar', 1, NULL, '2019-09-04 09:41:18', NULL),
        (9, 'Kab. Pidie', 1, NULL, '2019-09-04 09:41:18', NULL),
        (10, 'Kab. Bireuen', 1, NULL, '2019-09-04 09:41:18', NULL),
        (11, 'Kab. Aceh Utara', 1, NULL, '2019-09-04 09:41:18', NULL),
        (12, 'Kab. Aceh Barat Daya', 1, NULL, '2019-09-04 09:41:18', NULL),
        (13, 'Kab. Gayo Lues', 1, NULL, '2019-09-04 09:41:18', NULL),
        (14, 'Kab. Aceh Tamiang', 1, NULL, '2019-09-04 09:41:18', NULL),
        (15, 'Kab. Nagan Raya', 1, NULL, '2019-09-04 09:41:18', NULL),
        (16, 'Kab. Aceh Jaya', 1, NULL, '2019-09-04 09:41:18', NULL),
        (17, 'Kab. Bener Meriah', 1, NULL, '2019-09-04 09:41:18', NULL),
        (18, 'Kab. Pidie Jaya', 1, NULL, '2019-09-04 09:41:18', NULL),
        (19, 'Kota Banda Aceh', 1, NULL, '2019-09-04 09:41:18', NULL),
        (20, 'Kota Sabang', 1, NULL, '2019-09-04 09:41:18', NULL),
        (21, 'Kota Langsa', 1, NULL, '2019-09-04 09:41:18', NULL),
        (22, 'Kota Lhokseumawe', 1, NULL, '2019-09-04 09:41:18', NULL),
        (23, 'Kota Subulussalam', 1, NULL, '2019-09-04 09:41:18', NULL),
        (24, 'Kab. Nias', 2, NULL, NULL, NULL),
        (25, 'Kab. Mandailing Natal', 2, NULL, NULL, NULL),
        (26, 'Kab. Tapanuli Selatan', 2, NULL, NULL, NULL),
        (27, 'Kab. Tapanuli Tengah', 2, NULL, NULL, NULL),
        (28, 'Kab. Tapanuli Utara', 2, NULL, NULL, NULL),
        (29, 'Kab. Toba Samosir', 2, NULL, NULL, NULL),
        (30, 'Kab. Labuhan Batu', 2, NULL, NULL, NULL),
        (31, 'Kab. Asahan', 2, NULL, NULL, NULL),
        (32, 'Kab. Simalungun', 2, NULL, NULL, NULL),
        (33, 'Kab. Dairi', 2, NULL, NULL, NULL),
        (34, 'Kab. Karo', 2, NULL, NULL, NULL),
        (35, 'Kab. Deli Serdang', 2, NULL, NULL, NULL),
        (36, 'Kab. Langkat', 2, NULL, NULL, NULL),
        (37, 'Kab. Nias Selatan', 2, NULL, NULL, NULL),
        (38, 'Kab. Humbang Hasundutan', 2, NULL, NULL, NULL),
        (39, 'Kab. Pakpak Bharat', 2, NULL, NULL, NULL),
        (40, 'Kab. Samosir', 2, NULL, NULL, NULL),
        (41, 'Kab. Serdang Bedagai', 2, NULL, NULL, NULL),
        (42, 'Kab. Batu Bara', 2, NULL, NULL, NULL),
        (43, 'Kab. Padang Lawas Utara', 2, NULL, NULL, NULL),
        (44, 'Kab. Padang Lawas', 2, NULL, NULL, NULL),
        (45, 'Kab. Labuhan Batu Selatan', 2, NULL, NULL, NULL),
        (46, 'Kab. Labuhan Batu Utara', 2, NULL, NULL, NULL),
        (47, 'Kab. Nias Utara', 2, NULL, NULL, NULL),
        (48, 'Kab. Nias Barat', 2, NULL, NULL, NULL),
        (49, 'Kota Sibolga', 2, NULL, NULL, NULL),
        (50, 'Kota Tanjung Balai', 2, NULL, NULL, NULL),
        (51, 'Kota Pematang Siantar', 2, NULL, NULL, NULL),
        (52, 'Kota Tebing Tinggi', 2, NULL, NULL, NULL),
        (53, 'Kota Medan', 2, NULL, NULL, NULL),
        (54, 'Kota Binjai', 2, NULL, NULL, NULL),
        (55, 'Kota Padangsidimpuan', 2, NULL, NULL, NULL),
        (56, 'Kota Gunungsitoli', 2, NULL, NULL, NULL),
        (57, 'Kab. Kepulauan Mentawai', 3, NULL, NULL, NULL),
        (58, 'Kab. Pesisir Selatan', 3, NULL, NULL, NULL),
        (59, 'Kab. Solok', 3, NULL, NULL, NULL),
        (60, 'Kab. Sijunjung', 3, NULL, NULL, NULL),
        (61, 'Kab. Tanah Datar', 3, NULL, NULL, NULL),
        (62, 'Kab. Padang Pariaman', 3, NULL, NULL, NULL),
        (63, 'Kab. Agam', 3, NULL, NULL, NULL),
        (64, 'Kab. Lima Puluh Kota', 3, NULL, NULL, NULL),
        (65, 'Kab. Pasaman', 3, NULL, NULL, NULL),
        (66, 'Kab. Solok Selatan', 3, NULL, NULL, NULL),
        (67, 'Kab. Dharmasraya', 3, NULL, NULL, NULL),
        (68, 'Kab. Pasaman Barat', 3, NULL, NULL, NULL),
        (69, 'Kota Padang', 3, NULL, NULL, NULL),
        (70, 'Kota Solok', 3, NULL, NULL, NULL),
        (71, 'Kota Sawah Lunto', 3, NULL, NULL, NULL),
        (72, 'Kota Padang Panjang', 3, NULL, NULL, NULL),
        (73, 'Kota Bukittinggi', 3, NULL, NULL, NULL),
        (74, 'Kota Payakumbuh', 3, NULL, NULL, NULL),
        (75, 'Kota Pariaman', 3, NULL, NULL, NULL),
        (76, 'Kab. Kuantan Singingi', 4, NULL, NULL, NULL),
        (77, 'Kab. Indragiri Hulu', 4, NULL, NULL, NULL),
        (78, 'Kab. Indragiri Hilir', 4, NULL, NULL, NULL),
        (79, 'Kab. Pelalawan', 4, NULL, NULL, NULL),
        (80, 'Kab. S I A K', 4, NULL, NULL, NULL),
        (81, 'Kab. Kampar', 4, NULL, NULL, NULL),
        (82, 'Kab. Rokan Hulu', 4, NULL, NULL, NULL),
        (83, 'Kab. Bengkalis', 4, NULL, NULL, NULL),
        (84, 'Kab. Rokan Hilir', 4, NULL, NULL, NULL),
        (85, 'Kab. Kepulauan Meranti', 4, NULL, NULL, NULL),
        (86, 'Kota Pekanbaru', 4, NULL, NULL, NULL),
        (87, 'Kota D U M A I', 4, NULL, NULL, NULL),
        (88, 'Kab. Kerinci', 5, NULL, NULL, NULL),
        (89, 'Kab. Merangin', 5, NULL, NULL, NULL),
        (90, 'Kab. Sarolangun', 5, NULL, NULL, NULL),
        (91, 'Kab. Batang Hari', 5, NULL, NULL, NULL),
        (92, 'Kab. Muaro Jambi', 5, NULL, NULL, NULL),
        (93, 'Kab. Tanjung Jabung Timur', 5, NULL, NULL, NULL),
        (94, 'Kab. Tanjung Jabung Barat', 5, NULL, NULL, NULL),
        (95, 'Kab. Tebo', 5, NULL, NULL, NULL),
        (96, 'Kab. Bungo', 5, NULL, NULL, NULL),
        (97, 'Kota Jambi', 5, NULL, NULL, NULL),
        (98, 'Kota Sungai Penuh', 5, NULL, NULL, NULL),
        (99, 'Kab. Ogan Komering Ulu', 6, NULL, NULL, NULL),
        (100, 'Kab. Ogan Komering Ilir', 6, NULL, NULL, NULL),
        (101, 'Kab. Muara Enim', 6, NULL, NULL, NULL),
        (102, 'Kab. Lahat', 6, NULL, NULL, NULL),
        (103, 'Kab. Musi Rawas', 6, NULL, NULL, NULL),
        (104, 'Kab. Musi Banyuasin', 6, NULL, NULL, NULL),
        (105, 'Kab. Banyu Asin', 6, NULL, NULL, NULL),
        (106, 'Kab. Ogan Komering Ulu Selatan', 6, NULL, NULL, NULL),
        (107, 'Kab. Ogan Komering Ulu Timur', 6, NULL, NULL, NULL),
        (108, 'Kab. Ogan Ilir', 6, NULL, NULL, NULL),
        (109, 'Kab. Empat Lawang', 6, NULL, NULL, NULL),
        (110, 'Kota Palembang', 6, NULL, NULL, NULL),
        (111, 'Kota Prabumulih', 6, NULL, NULL, NULL),
        (112, 'Kota Pagar Alam', 6, NULL, NULL, NULL),
        (113, 'Kota Lubuklinggau', 6, NULL, NULL, NULL),
        (114, 'Kab. Bengkulu Selatan', 7, NULL, NULL, NULL),
        (115, 'Kab. Rejang Lebong', 7, NULL, NULL, NULL),
        (116, 'Kab. Bengkulu Utara', 7, NULL, NULL, NULL),
        (117, 'Kab. Kaur', 7, NULL, NULL, NULL),
        (118, 'Kab. Seluma', 7, NULL, NULL, NULL),
        (119, 'Kab. Mukomuko', 7, NULL, NULL, NULL),
        (120, 'Kab. Lebong', 7, NULL, NULL, NULL),
        (121, 'Kab. Kepahiang', 7, NULL, NULL, NULL),
        (122, 'Kab. Bengkulu Tengah', 7, NULL, NULL, NULL),
        (123, 'Kota Bengkulu', 7, NULL, NULL, NULL),
        (124, 'Kab. Lampung Barat', 8, NULL, NULL, NULL),
        (125, 'Kab. Tanggamus', 8, NULL, NULL, NULL),
        (126, 'Kab. Lampung Selatan', 8, NULL, NULL, NULL),
        (127, 'Kab. Lampung Timur', 8, NULL, NULL, NULL),
        (128, 'Kab. Lampung Tengah', 8, NULL, NULL, NULL),
        (129, 'Kab. Lampung Utara', 8, NULL, NULL, NULL),
        (130, 'Kab. Way Kanan', 8, NULL, NULL, NULL),
        (131, 'Kab. Tulangbawang', 8, NULL, NULL, NULL),
        (132, 'Kab. Pesawaran', 8, NULL, NULL, NULL),
        (133, 'Kab. Pringsewu', 8, NULL, NULL, NULL),
        (134, 'Kab. Mesuji', 8, NULL, NULL, NULL),
        (135, 'Kab. Tulang Bawang Barat', 8, NULL, NULL, NULL),
        (136, 'Kab. Pesisir Barat', 8, NULL, NULL, NULL),
        (137, 'Kota Bandar Lampung', 8, NULL, NULL, NULL),
        (138, 'Kota Metro', 8, NULL, NULL, NULL),
        (139, 'Kab. Bangka', 9, NULL, NULL, NULL),
        (140, 'Kab. Belitung', 9, NULL, NULL, NULL),
        (141, 'Kab. Bangka Barat', 9, NULL, NULL, NULL),
        (142, 'Kab. Bangka Tengah', 9, NULL, NULL, NULL),
        (143, 'Kab. Bangka Selatan', 9, NULL, NULL, NULL),
        (144, 'Kab. Belitung Timur', 9, NULL, NULL, NULL),
        (145, 'Kota Pangkal Pinang', 9, NULL, NULL, NULL),
        (146, 'Kab. Karimun', 10, NULL, NULL, NULL),
        (147, 'Kab. Bintan', 10, NULL, NULL, NULL),
        (148, 'Kab. Natuna', 10, NULL, NULL, NULL),
        (149, 'Kab. Lingga', 10, NULL, NULL, NULL),
        (150, 'Kab. Kepulauan Anambas', 10, NULL, NULL, NULL),
        (151, 'Kota B A T A M', 10, NULL, NULL, NULL),
        (152, 'Kota Tanjung Pinang', 10, NULL, NULL, NULL),
        (153, 'Kab. Kepulauan Seribu', 11, NULL, NULL, NULL),
        (154, 'Kota Jakarta Selatan', 11, NULL, NULL, NULL),
        (155, 'Kota Jakarta Timur', 11, NULL, NULL, NULL),
        (156, 'Kota Jakarta Pusat', 11, NULL, NULL, NULL),
        (157, 'Kota Jakarta Barat', 11, NULL, NULL, NULL),
        (158, 'Kota Jakarta Utara', 11, NULL, NULL, NULL),
        (159, 'Kab. Bogor', 12, NULL, NULL, NULL),
        (160, 'Kab. Sukabumi', 12, NULL, NULL, NULL),
        (161, 'Kab. Cianjur', 12, NULL, NULL, NULL),
        (162, 'Kab. Bandung', 12, NULL, NULL, NULL),
        (163, 'Kab. Garut', 12, NULL, NULL, NULL),
        (164, 'Kab. Tasikmalaya', 12, NULL, NULL, NULL),
        (165, 'Kab. Ciamis', 12, NULL, NULL, NULL),
        (166, 'Kab. Kuningan', 12, NULL, NULL, NULL),
        (167, 'Kab. Cirebon', 12, NULL, NULL, NULL),
        (168, 'Kab. Majalengka', 12, NULL, NULL, NULL),
        (169, 'Kab. Sumedang', 12, NULL, NULL, NULL),
        (170, 'Kab. Indramayu', 12, NULL, NULL, NULL),
        (171, 'Kab. Subang', 12, NULL, NULL, NULL),
        (172, 'Kab. Purwakarta', 12, NULL, NULL, NULL),
        (173, 'Kab. Karawang', 12, NULL, NULL, NULL),
        (174, 'Kab. Bekasi', 12, NULL, NULL, NULL),
        (175, 'Kab. Bandung Barat', 12, NULL, NULL, NULL),
        (176, 'Kab. Pangandaran', 12, NULL, NULL, NULL),
        (177, 'Kota Bogor', 12, NULL, NULL, NULL),
        (178, 'Kota Sukabumi', 12, NULL, NULL, NULL),
        (179, 'Kota Bandung', 12, NULL, NULL, NULL),
        (180, 'Kota Cirebon', 12, NULL, NULL, NULL),
        (181, 'Kota Bekasi', 12, NULL, NULL, NULL),
        (182, 'Kota Depok', 12, NULL, NULL, NULL),
        (183, 'Kota Cimahi', 12, NULL, NULL, NULL),
        (184, 'Kota Tasikmalaya', 12, NULL, NULL, NULL),
        (185, 'Kota Banjar', 12, NULL, NULL, NULL),
        (186, 'Kab. Cilacap', 13, NULL, NULL, NULL),
        (187, 'Kab. Banyumas', 13, NULL, NULL, NULL),
        (188, 'Kab. Purbalingga', 13, NULL, NULL, NULL),
        (189, 'Kab. Banjarnegara', 13, NULL, NULL, NULL),
        (190, 'Kab. Kebumen', 13, NULL, NULL, NULL),
        (191, 'Kab. Purworejo', 13, NULL, NULL, NULL),
        (192, 'Kab. Wonosobo', 13, NULL, NULL, NULL),
        (193, 'Kab. Magelang', 13, NULL, NULL, NULL),
        (194, 'Kab. Boyolali', 13, NULL, NULL, NULL),
        (195, 'Kab. Klaten', 13, NULL, NULL, NULL),
        (196, 'Kab. Sukoharjo', 13, NULL, NULL, NULL),
        (197, 'Kab. Wonogiri', 13, NULL, NULL, NULL),
        (198, 'Kab. Karanganyar', 13, NULL, NULL, NULL),
        (199, 'Kab. Sragen', 13, NULL, NULL, NULL),
        (200, 'Kab. Grobogan', 13, NULL, NULL, NULL),
        (201, 'Kab. Blora', 13, NULL, NULL, NULL),
        (202, 'Kab. Rembang', 13, NULL, NULL, NULL),
        (203, 'Kab. Pati', 13, NULL, NULL, NULL),
        (204, 'Kab. Kudus', 13, NULL, NULL, NULL),
        (205, 'Kab. Jepara', 13, NULL, NULL, NULL),
        (206, 'Kab. Demak', 13, NULL, NULL, NULL),
        (207, 'Kab. Semarang', 13, NULL, NULL, NULL),
        (208, 'Kab. Temanggung', 13, NULL, NULL, NULL),
        (209, 'Kab. Kendal', 13, NULL, NULL, NULL),
        (210, 'Kab. Batang', 13, NULL, NULL, NULL),
        (211, 'Kab. Pekalongan', 13, NULL, NULL, NULL),
        (212, 'Kab. Pemalang', 13, NULL, NULL, NULL),
        (213, 'Kab. Tegal', 13, NULL, NULL, NULL),
        (214, 'Kab. Brebes', 13, NULL, NULL, NULL),
        (215, 'Kota Magelang', 13, NULL, NULL, NULL),
        (216, 'Kota Surakarta', 13, NULL, NULL, NULL),
        (217, 'Kota Salatiga', 13, NULL, NULL, NULL),
        (218, 'Kota Semarang', 13, NULL, NULL, NULL),
        (219, 'Kota Pekalongan', 13, NULL, NULL, NULL),
        (220, 'Kota Tegal', 13, NULL, NULL, NULL),
        (221, 'Kab. Kulon Progo', 14, NULL, NULL, NULL),
        (222, 'Kab. Bantul', 14, NULL, NULL, NULL),
        (223, 'Kab. Gunung Kidul', 14, NULL, NULL, NULL),
        (224, 'Kab. Sleman', 14, NULL, NULL, NULL),
        (225, 'Kota Yogyakarta', 14, NULL, NULL, NULL),
        (226, 'Kab. Pacitan', 15, NULL, NULL, NULL),
        (227, 'Kab. Ponorogo', 15, NULL, NULL, NULL),
        (228, 'Kab. Trenggalek', 15, NULL, NULL, NULL),
        (229, 'Kab. Tulungagung', 15, NULL, NULL, NULL),
        (230, 'Kab. Blitar', 15, NULL, NULL, NULL),
        (231, 'Kab. Kediri', 15, NULL, NULL, NULL),
        (232, 'Kab. Malang', 15, NULL, NULL, NULL),
        (233, 'Kab. Lumajang', 15, NULL, NULL, NULL),
        (234, 'Kab. Jember', 15, NULL, NULL, NULL),
        (235, 'Kab. Banyuwangi', 15, NULL, NULL, NULL),
        (236, 'Kab. Bondowoso', 15, NULL, NULL, NULL),
        (237, 'Kab. Situbondo', 15, NULL, NULL, NULL),
        (238, 'Kab. Probolinggo', 15, NULL, NULL, NULL),
        (239, 'Kab. Pasuruan', 15, NULL, NULL, NULL),
        (240, 'Kab. Sidoarjo', 15, NULL, NULL, NULL),
        (241, 'Kab. Mojokerto', 15, NULL, NULL, NULL),
        (242, 'Kab. Jombang', 15, NULL, NULL, NULL),
        (243, 'Kab. Nganjuk', 15, NULL, NULL, NULL),
        (244, 'Kab. Madiun', 15, NULL, NULL, NULL),
        (245, 'Kab. Magetan', 15, NULL, NULL, NULL),
        (246, 'Kab. Ngawi', 15, NULL, NULL, NULL),
        (247, 'Kab. Bojonegoro', 15, NULL, NULL, NULL),
        (248, 'Kab. Tuban', 15, NULL, NULL, NULL),
        (249, 'Kab. Lamongan', 15, NULL, NULL, NULL),
        (250, 'Kab. Gresik', 15, NULL, NULL, NULL),
        (251, 'Kab. Bangkalan', 15, NULL, NULL, NULL),
        (252, 'Kab. Sampang', 15, NULL, NULL, NULL),
        (253, 'Kab. Pamekasan', 15, NULL, NULL, NULL),
        (254, 'Kab. Sumenep', 15, NULL, NULL, NULL),
        (255, 'Kota Kediri', 15, NULL, NULL, NULL),
        (256, 'Kota Blitar', 15, NULL, NULL, NULL),
        (257, 'Kota Malang', 15, NULL, NULL, NULL),
        (258, 'Kota Probolinggo', 15, NULL, NULL, NULL),
        (259, 'Kota Pasuruan', 15, NULL, NULL, NULL),
        (260, 'Kota Mojokerto', 15, NULL, NULL, NULL),
        (261, 'Kota Madiun', 15, NULL, NULL, NULL),
        (262, 'Kota Surabaya', 15, NULL, NULL, NULL),
        (263, 'Kota Batu', 15, NULL, NULL, NULL),
        (264, 'Kab. Pandeglang', 16, NULL, NULL, NULL),
        (265, 'Kab. Lebak', 16, NULL, NULL, NULL),
        (266, 'Kab. Tangerang', 16, NULL, NULL, NULL),
        (267, 'Kab. Serang', 16, NULL, NULL, NULL),
        (268, 'Kota Tangerang', 16, NULL, NULL, NULL),
        (269, 'Kota Cilegon', 16, NULL, NULL, NULL),
        (270, 'Kota Serang', 16, NULL, NULL, NULL),
        (271, 'Kota Tangerang Selatan', 16, NULL, NULL, NULL),
        (272, 'Kab. Jembrana', 17, NULL, NULL, NULL),
        (273, 'Kab. Tabanan', 17, NULL, NULL, NULL),
        (274, 'Kab. Badung', 17, NULL, NULL, NULL),
        (275, 'Kab. Gianyar', 17, NULL, NULL, NULL),
        (276, 'Kab. Klungkung', 17, NULL, NULL, NULL),
        (277, 'Kab. Bangli', 17, NULL, NULL, NULL),
        (278, 'Kab. Karang Asem', 17, NULL, NULL, NULL),
        (279, 'Kab. Buleleng', 17, NULL, NULL, NULL),
        (280, 'Kota Denpasar', 17, NULL, NULL, NULL),
        (281, 'Kab. Lombok Barat', 18, NULL, NULL, NULL),
        (282, 'Kab. Lombok Tengah', 18, NULL, NULL, NULL),
        (283, 'Kab. Lombok Timur', 18, NULL, NULL, NULL),
        (284, 'Kab. Sumbawa', 18, NULL, NULL, NULL),
        (285, 'Kab. Dompu', 18, NULL, NULL, NULL),
        (286, 'Kab. Bima', 18, NULL, NULL, NULL),
        (287, 'Kab. Sumbawa Barat', 18, NULL, NULL, NULL),
        (288, 'Kab. Lombok Utara', 18, NULL, NULL, NULL),
        (289, 'Kota Mataram', 18, NULL, NULL, NULL),
        (290, 'Kota Bima', 18, NULL, NULL, NULL),
        (291, 'Kab. Sumba Barat', 19, NULL, NULL, NULL),
        (292, 'Kab. Sumba Timur', 19, NULL, NULL, NULL),
        (293, 'Kab. Kupang', 19, NULL, NULL, NULL),
        (294, 'Kab. Timor Tengah Selatan', 19, NULL, NULL, NULL),
        (295, 'Kab. Timor Tengah Utara', 19, NULL, NULL, NULL),
        (296, 'Kab. Belu', 19, NULL, NULL, NULL),
        (297, 'Kab. Alor', 19, NULL, NULL, NULL),
        (298, 'Kab. Lembata', 19, NULL, NULL, NULL),
        (299, 'Kab. Flores Timur', 19, NULL, NULL, NULL),
        (300, 'Kab. Sikka', 19, NULL, NULL, NULL),
        (301, 'Kab. Ende', 19, NULL, NULL, NULL),
        (302, 'Kab. Ngada', 19, NULL, NULL, NULL),
        (303, 'Kab. Manggarai', 19, NULL, NULL, NULL),
        (304, 'Kab. Rote Ndao', 19, NULL, NULL, NULL),
        (305, 'Kab. Manggarai Barat', 19, NULL, NULL, NULL),
        (306, 'Kab. Sumba Tengah', 19, NULL, NULL, NULL),
        (307, 'Kab. Sumba Barat Daya', 19, NULL, NULL, NULL),
        (308, 'Kab. Nagekeo', 19, NULL, NULL, NULL),
        (309, 'Kab. Manggarai Timur', 19, NULL, NULL, NULL),
        (310, 'Kab. Sabu Raijua', 19, NULL, NULL, NULL),
        (311, 'Kota Kupang', 19, NULL, NULL, NULL),
        (312, 'Kab. Sambas', 20, NULL, NULL, NULL),
        (313, 'Kab. Bengkayang', 20, NULL, NULL, NULL),
        (314, 'Kab. Landak', 20, NULL, NULL, NULL),
        (315, 'Kab. Pontianak', 20, NULL, NULL, NULL),
        (316, 'Kab. Sanggau', 20, NULL, NULL, NULL),
        (317, 'Kab. Ketapang', 20, NULL, NULL, NULL),
        (318, 'Kab. Sintang', 20, NULL, NULL, NULL),
        (319, 'Kab. Kapuas Hulu', 20, NULL, NULL, NULL),
        (320, 'Kab. Sekadau', 20, NULL, NULL, NULL),
        (321, 'Kab. Melawi', 20, NULL, NULL, NULL),
        (322, 'Kab. Kayong Utara', 20, NULL, NULL, NULL),
        (323, 'Kab. Kubu Raya', 20, NULL, NULL, NULL),
        (324, 'Kota Pontianak', 20, NULL, NULL, NULL),
        (325, 'Kota Singkawang', 20, NULL, NULL, NULL),
        (326, 'Kab. Kotawaringin Barat', 21, NULL, NULL, NULL),
        (327, 'Kab. Kotawaringin Timur', 21, NULL, NULL, NULL),
        (328, 'Kab. Kapuas', 21, NULL, NULL, NULL),
        (329, 'Kab. Barito Selatan', 21, NULL, NULL, NULL),
        (330, 'Kab. Barito Utara', 21, NULL, NULL, NULL),
        (331, 'Kab. Sukamara', 21, NULL, NULL, NULL),
        (332, 'Kab. Lamandau', 21, NULL, NULL, NULL),
        (333, 'Kab. Seruyan', 21, NULL, NULL, NULL),
        (334, 'Kab. Katingan', 21, NULL, NULL, NULL),
        (335, 'Kab. Pulang Pisau', 21, NULL, NULL, NULL),
        (336, 'Kab. Gunung Mas', 21, NULL, NULL, NULL),
        (337, 'Kab. Barito Timur', 21, NULL, NULL, NULL),
        (338, 'Kab. Murung Raya', 21, NULL, NULL, NULL),
        (339, 'Kota Palangka Raya', 21, NULL, NULL, NULL),
        (340, 'Kab. Tanah Laut', 22, NULL, NULL, NULL),
        (341, 'Kab. Kota Baru', 22, NULL, NULL, NULL),
        (342, 'Kab. Banjar', 22, NULL, NULL, NULL),
        (343, 'Kab. Barito Kuala', 22, NULL, NULL, NULL),
        (344, 'Kab. Tapin', 22, NULL, NULL, NULL),
        (345, 'Kab. Hulu Sungai Selatan', 22, NULL, NULL, NULL),
        (346, 'Kab. Hulu Sungai Tengah', 22, NULL, NULL, NULL),
        (347, 'Kab. Hulu Sungai Utara', 22, NULL, NULL, NULL),
        (348, 'Kab. Tabalong', 22, NULL, NULL, NULL),
        (349, 'Kab. Tanah Bumbu', 22, NULL, NULL, NULL),
        (350, 'Kab. Balangan', 22, NULL, NULL, NULL),
        (351, 'Kota Banjarmasin', 22, NULL, NULL, NULL),
        (352, 'Kota Banjar Baru', 22, NULL, NULL, NULL),
        (353, 'Kab. Paser', 23, NULL, NULL, NULL),
        (354, 'Kab. Kutai Barat', 23, NULL, NULL, NULL),
        (355, 'Kab. Kutai Kartanegara', 23, NULL, NULL, NULL),
        (356, 'Kab. Kutai Timur', 23, NULL, NULL, NULL),
        (357, 'Kab. Berau', 23, NULL, NULL, NULL),
        (358, 'Kab. Penajam Paser Utara', 23, NULL, NULL, NULL),
        (359, 'Kota Balikpapan', 23, NULL, NULL, NULL),
        (360, 'Kota Samarinda', 23, NULL, NULL, NULL),
        (361, 'Kota Bontang', 23, NULL, NULL, NULL),
        (362, 'Kab. Malinau', 24, NULL, NULL, NULL),
        (363, 'Kab. Bulungan', 24, NULL, NULL, NULL),
        (364, 'Kab. Tana Tidung', 24, NULL, NULL, NULL),
        (365, 'Kab. Nunukan', 24, NULL, NULL, NULL),
        (366, 'Kota Tarakan', 24, NULL, NULL, NULL),
        (367, 'Kab. Bolaang Mongondow', 25, NULL, NULL, NULL),
        (368, 'Kab. Minahasa', 25, NULL, NULL, NULL),
        (369, 'Kab. Kepulauan Sangihe', 25, NULL, NULL, NULL),
        (370, 'Kab. Kepulauan Talaud', 25, NULL, NULL, NULL),
        (371, 'Kab. Minahasa Selatan', 25, NULL, NULL, NULL),
        (372, 'Kab. Minahasa Utara', 25, NULL, NULL, NULL),
        (373, 'Kab. Bolaang Mongondow Utara', 25, NULL, NULL, NULL),
        (374, 'Kab. Siau Tagulandang Biaro', 25, NULL, NULL, NULL),
        (375, 'Kab. Minahasa Tenggara', 25, NULL, NULL, NULL),
        (376, 'Kab. Bolaang Mongondow Selatan', 25, NULL, NULL, NULL),
        (377, 'Kab. Bolaang Mongondow Timur', 25, NULL, NULL, NULL),
        (378, 'Kota Manado', 25, NULL, NULL, NULL),
        (379, 'Kota Bitung', 25, NULL, NULL, NULL),
        (380, 'Kota Tomohon', 25, NULL, NULL, NULL),
        (381, 'Kota Kotamobagu', 25, NULL, NULL, NULL),
        (382, 'Kab. Banggai Kepulauan', 26, NULL, NULL, NULL),
        (383, 'Kab. Banggai', 26, NULL, NULL, NULL),
        (384, 'Kab. Morowali', 26, NULL, NULL, NULL),
        (385, 'Kab. Poso', 26, NULL, NULL, NULL),
        (386, 'Kab. Donggala', 26, NULL, NULL, NULL),
        (387, 'Kab. Toli-toli', 26, NULL, NULL, NULL),
        (388, 'Kab. Buol', 26, NULL, NULL, NULL),
        (389, 'Kab. Parigi Moutong', 26, NULL, NULL, NULL),
        (390, 'Kab. Tojo Una-una', 26, NULL, NULL, NULL),
        (391, 'Kab. Sigi', 26, NULL, NULL, NULL),
        (392, 'Kota Palu', 26, NULL, NULL, NULL),
        (393, 'Kab. Kepulauan Selayar', 27, NULL, NULL, NULL),
        (394, 'Kab. Bulukumba', 27, NULL, NULL, NULL),
        (395, 'Kab. Bantaeng', 27, NULL, NULL, NULL),
        (396, 'Kab. Jeneponto', 27, NULL, NULL, NULL),
        (397, 'Kab. Takalar', 27, NULL, NULL, NULL),
        (398, 'Kab. Gowa', 27, NULL, NULL, NULL),
        (399, 'Kab. Sinjai', 27, NULL, NULL, NULL),
        (400, 'Kab. Maros', 27, NULL, NULL, NULL),
        (401, 'Kab. Pangkajene Dan Kepulauan', 27, NULL, NULL, NULL),
        (402, 'Kab. Barru', 27, NULL, NULL, NULL),
        (403, 'Kab. Bone', 27, NULL, NULL, NULL),
        (404, 'Kab. Soppeng', 27, NULL, NULL, NULL),
        (405, 'Kab. Wajo', 27, NULL, NULL, NULL),
        (406, 'Kab. Sidenreng Rappang', 27, NULL, NULL, NULL),
        (407, 'Kab. Pinrang', 27, NULL, NULL, NULL),
        (408, 'Kab. Enrekang', 27, NULL, NULL, NULL),
        (409, 'Kab. Luwu', 27, NULL, NULL, NULL),
        (410, 'Kab. Tana Toraja', 27, NULL, NULL, NULL),
        (411, 'Kab. Luwu Utara', 27, NULL, NULL, NULL),
        (412, 'Kab. Luwu Timur', 27, NULL, NULL, NULL),
        (413, 'Kab. Toraja Utara', 27, NULL, NULL, NULL),
        (414, 'Kota Makassar', 27, NULL, NULL, NULL),
        (415, 'Kota Parepare', 27, NULL, NULL, NULL),
        (416, 'Kota Palopo', 27, NULL, NULL, NULL),
        (417, 'Kab. Buton', 28, NULL, NULL, NULL),
        (418, 'Kab. Muna', 28, NULL, NULL, NULL),
        (419, 'Kab. Konawe', 28, NULL, NULL, NULL),
        (420, 'Kab. Kolaka', 28, NULL, NULL, NULL),
        (421, 'Kab. Konawe Selatan', 28, NULL, NULL, NULL),
        (422, 'Kab. Bombana', 28, NULL, NULL, NULL),
        (423, 'Kab. Wakatobi', 28, NULL, NULL, NULL),
        (424, 'Kab. Kolaka Utara', 28, NULL, NULL, NULL),
        (425, 'Kab. Buton Utara', 28, NULL, NULL, NULL),
        (426, 'Kab. Konawe Utara', 28, NULL, NULL, NULL),
        (427, 'Kota Kendari', 28, NULL, NULL, NULL),
        (428, 'Kota Baubau', 28, NULL, NULL, NULL),
        (429, 'Kab. Boalemo', 29, NULL, NULL, NULL),
        (430, 'Kab. Gorontalo', 29, NULL, NULL, NULL),
        (431, 'Kab. Pohuwato', 29, NULL, NULL, NULL),
        (432, 'Kab. Bone Bolango', 29, NULL, NULL, NULL),
        (433, 'Kab. Gorontalo Utara', 29, NULL, NULL, NULL),
        (434, 'Kota Gorontalo', 29, NULL, NULL, NULL),
        (435, 'Kab. Majene', 30, NULL, NULL, NULL),
        (436, 'Kab. Polewali Mandar', 30, NULL, NULL, NULL),
        (437, 'Kab. Mamasa', 30, NULL, NULL, NULL),
        (438, 'Kab. Mamuju', 30, NULL, NULL, NULL),
        (439, 'Kab. Mamuju Utara', 30, NULL, NULL, NULL),
        (440, 'Kab. Maluku Tenggara Barat', 31, NULL, NULL, NULL),
        (441, 'Kab. Maluku Tenggara', 31, NULL, NULL, NULL),
        (442, 'Kab. Maluku Tengah', 31, NULL, NULL, NULL),
        (443, 'Kab. Buru', 31, NULL, NULL, NULL),
        (444, 'Kab. Kepulauan Aru', 31, NULL, NULL, NULL),
        (445, 'Kab. Seram Bagian Barat', 31, NULL, NULL, NULL),
        (446, 'Kab. Seram Bagian Timur', 31, NULL, NULL, NULL),
        (447, 'Kab. Maluku Barat Daya', 31, NULL, NULL, NULL),
        (448, 'Kab. Buru Selatan', 31, NULL, NULL, NULL),
        (449, 'Kota Ambon', 31, NULL, NULL, NULL),
        (450, 'Kota Tual', 31, NULL, NULL, NULL),
        (451, 'Kab. Halmahera Barat', 32, NULL, NULL, NULL),
        (452, 'Kab. Halmahera Tengah', 32, NULL, NULL, NULL),
        (453, 'Kab. Kepulauan Sula', 32, NULL, NULL, NULL),
        (454, 'Kab. Halmahera Selatan', 32, NULL, NULL, NULL),
        (455, 'Kab. Halmahera Utara', 32, NULL, NULL, NULL),
        (456, 'Kab. Halmahera Timur', 32, NULL, NULL, NULL),
        (457, 'Kab. Pulau Morotai', 32, NULL, NULL, NULL),
        (458, 'Kota Ternate', 32, NULL, NULL, NULL),
        (459, 'Kota Tidore Kepulauan', 32, NULL, NULL, NULL),
        (460, 'Kab. Fakfak', 33, NULL, NULL, NULL),
        (461, 'Kab. Kaimana', 33, NULL, NULL, NULL),
        (462, 'Kab. Teluk Wondama', 33, NULL, NULL, NULL),
        (463, 'Kab. Teluk Bintuni', 33, NULL, NULL, NULL),
        (464, 'Kab. Manokwari', 33, NULL, NULL, NULL),
        (465, 'Kab. Sorong Selatan', 33, NULL, NULL, NULL),
        (466, 'Kab. Sorong', 33, NULL, NULL, NULL),
        (467, 'Kab. Raja Ampat', 33, NULL, NULL, NULL),
        (468, 'Kab. Tambrauw', 33, NULL, NULL, NULL),
        (469, 'Kab. Maybrat', 33, NULL, NULL, NULL),
        (470, 'Kota Sorong', 33, NULL, NULL, NULL),
        (471, 'Kab. Merauke', 34, NULL, NULL, NULL),
        (472, 'Kab. Jayawijaya', 34, NULL, NULL, NULL),
        (473, 'Kab. Jayapura', 34, NULL, NULL, NULL),
        (474, 'Kab. Nabire', 34, NULL, NULL, NULL),
        (475, 'Kab. Kepulauan Yapen', 34, NULL, NULL, NULL),
        (476, 'Kab. Biak Numfor', 34, NULL, NULL, NULL),
        (477, 'Kab. Paniai', 34, NULL, NULL, NULL),
        (478, 'Kab. Puncak Jaya', 34, NULL, NULL, NULL),
        (479, 'Kab. Mimika', 34, NULL, NULL, NULL),
        (480, 'Kab. Boven Digoel', 34, NULL, NULL, NULL),
        (481, 'Kab. Mappi', 34, NULL, NULL, NULL),
        (482, 'Kab. Asmat', 34, NULL, NULL, NULL),
        (483, 'Kab. Yahukimo', 34, NULL, NULL, NULL),
        (484, 'Kab. Pegunungan Bintang', 34, NULL, NULL, NULL),
        (485, 'Kab. Tolikara', 34, NULL, NULL, NULL),
        (486, 'Kab. Sarmi', 34, NULL, NULL, NULL),
        (487, 'Kab. Keerom', 34, NULL, NULL, NULL),
        (488, 'Kab. Waropen', 34, NULL, NULL, NULL),
        (489, 'Kab. Supiori', 34, NULL, NULL, NULL),
        (490, 'Kab. Mamberamo Raya', 34, NULL, NULL, NULL),
        (491, 'Kab. Nduga', 34, NULL, NULL, NULL),
        (492, 'Kab. Lanny Jaya', 34, NULL, NULL, NULL),
        (493, 'Kab. Mamberamo Tengah', 34, NULL, NULL, NULL),
        (494, 'Kab. Yalimo', 34, NULL, NULL, NULL),
        (495, 'Kab. Puncak', 34, NULL, NULL, NULL),
        (496, 'Kab. Dogiyai', 34, NULL, NULL, NULL),
        (497, 'Kab. Intan Jaya', 34, NULL, NULL, NULL),
        (498, 'Kab. Deiyai', 34, NULL, NULL, NULL),
        (499, 'Kota Jayapura', 34, NULL, NULL, NULL);
        "));
    }
}
